name: bakery actions
on:
  pull_request:
    paths:
      - '**'
jobs:
  bakery:
    name: "bakery build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup jdk"
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: "change wrapper permissions"
        run: chmod +x ./gradlew
      - name: "build with gradle"
        run: ./gradlew build